function showAlert(){alert("페이지생성 완료")}function sleep(t){return new Promise(n=>setTimeout(n,t))}async function makepage(n,t,o,e){var m=[],h=[],[n,s]=(t.상세내역.forEach(n=>{n.옵션1_이미지&&(h.push(n.옵션1_한국어),m.push(n.옵션1_이미지))}),await async function(n,t,i){console.log("setpage");var o=n[0].result[0],e=[],s=n[0].result[2],n=n[0].result[3],l=t.minimagepixel,c=t.maxthumbqty;async function r(n){var t,o;n.includes("https://")&&(o=n,t=await new Promise((n,t)=>{var i=new Image;i.src=o,i.onload=()=>n(i.width),i.onerror=t}),l<t)&&e.push(n)}for(a of s)await r(a);async function d(n,i){console.log("downloading");var t=new XMLHttpRequest;t.open("GET",n,!0),t.responseType="blob",t.onload=function(){var n=(window.URL||window.webkitURL).createObjectURL(this.response),t=document.createElement("a");t.href=n,t.download=i,document.body.appendChild(t),t.click(),document.body.removeChild(t)},t.send()}var g=0,p=0;if(console.log(n[0]),c>o.length)for(g=0;g<o.length;g++)0<o[g].search(".jpg")?d(o[g],i+"_"+(g+1).toString()+".jpg"):d(o[g],i+"_"+(g+1).toString()+".png");else for(g=0;g<c;g++)0<o[g].search(".jpg")?d(o[g],i+"_"+(g+1).toString()+".jpg"):d(o[g],i+"_"+(g+1).toString()+".png");if(console.log(h.length),console.log(m),"1688"==n[0])for(p=0;p<h.length;p++)void 0!==m[p]&&(0<m[p].search(".jpg")?(console.log(i+"_"+h[p]+".jpg"),d(m[p],i+"_"+h[p]+".jpg")):d(m[p],i+"_"+h[p]+".png"),await sleep(500));return[m,e]}(n,t,o)),[[l,c],n,s,t,o]=(console.log(n,s),[[n,s],t,o,h,e]),s=`              
        <canvas id="canvas" data-productnum="`+s+`" width="800" height="100"></canvas>
        <h1>
        `,n=n.mdcontent,r=t,d="";if(0==r.length)d="";else if(1==r.length)d="<tr>\n<td>\n<img class='optionimg' src='"+l[0]+"'>\n<div class='optiontext'>"+r+"</div>\n</td>\n</tr>";else if(r.length%2==0)for(i=0;i<r.length/2;i++)d=d+"<tr>\n<td>\n<img class='optionimg' src='"+l[2*i]+"'>\n<div class='optiontext'>"+r[2*i]+"</div>\n</td>\n<td>\n<img class='optionimg' src='"+l[2*i+1]+"'>\n<div class='optiontext'>"+r[2*i+1]+"</div>\n</td>\n</tr>";else{for(i=0;i<r.length/2-.5;i++)d=d+"<tr>\n<td>\n<img class='optionimg' src='"+l[2*i]+"'>\n<div class='optiontext'>"+r[2*i]+"</div>\n</td>\n<td>\n<img class='optionimg' src='"+l[2*i+1]+"'>\n<div class='optiontext'>"+r[2*i+1]+"</div>\n</td>\n</tr>";d=d+"<tr>\n<td>\n<img class='optionimg' src='"+l[r.length-1]+"'>\n<div class='optiontext'>"+r[r.length-1]+"</div>\n</td>\n</tr>"}var g="";for(i=0;i<c.length;i++)g=g+"<div class='container'>\n<img class='image' src='"+c[i]+"'>\n<img class='changed' src=\""+c[i]+"\" alt=''>\n<div class='closebutton'>X</div>\n</div>";t=s+o+'</h1><p class="md">'+n+`</p>
                      
                    <div class="container">
                        <table style="margin-left: auto; margin-right: auto; margin-bottom: 20px;">
                            <caption></caption>
        <tbody>
        `+d+`
        </tbody>
        </table>
        <div class="closebutton">X</div>
    </div>
    <h1></h1>
        `+g,document.querySelector(".main").innerHTML=t}